Repository sparta-4-s/For-Us-Market, pull requests merged in 2025-09, with the labels that each got.

#2 feat : 프로젝트 기본 구조 생성
  .gitignore
  build.gradle
  src/main/java/com/sparta/forusmarket/common/config/JpaAuditingConfig.java
  src/main/java/com/sparta/forusmarket/common/entity/BaseEntity.java
  src/main/java/com/sparta/forusmarket/common/exception/CommonErrorCode.java
  src/main/java/com/sparta/forusmarket/common/exception/ErrorCode.java
  src/main/java/com/sparta/forusmarket/common/exception/GlobalException.java
  src/main/java/com/sparta/forusmarket/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/forusmarket/common/response/ApiErrorResponse.java
  src/main/java/com/sparta/forusmarket/common/response/ApiPageResponse.java
  src/main/java/com/sparta/forusmarket/common/response/ApiResponse.java
  src/main/java/com/sparta/forusmarket/domain/order/entity/Order.java
  src/main/java/com/sparta/forusmarket/domain/order/enums/OrderStatus.java
  src/main/java/com/sparta/forusmarket/domain/product/entity/Product.java
  src/main/java/com/sparta/forusmarket/domain/product/enums/Category.java
  src/main/java/com/sparta/forusmarket/domain/user/controller/UserController.java
  src/main/java/com/sparta/forusmarket/domain/user/entity/Address.java
  src/main/java/com/sparta/forusmarket/domain/user/entity/User.java
  src/main/java/com/sparta/forusmarket/domain/user/exception/InvalidUserException.java
  src/main/java/com/sparta/forusmarket/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/forusmarket/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/forusmarket/domain/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨feat

#7 feat(security): spring security 추가
  build.gradle
  src/main/java/com/sparta/forusmarket/common/config/PropertiesConfig.java
  src/main/java/com/sparta/forusmarket/common/config/SecurityConfig.java
  src/main/java/com/sparta/forusmarket/common/enums/UserRole.java
  src/main/java/com/sparta/forusmarket/common/properties/JwtSecurityProperties.java
  src/main/java/com/sparta/forusmarket/common/security/dto/AuthUser.java
  src/main/java/com/sparta/forusmarket/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/forusmarket/common/security/filter/JwtAuthenticationToken.java
  src/main/java/com/sparta/forusmarket/common/security/utils/JwtUtil.java
  src/main/java/com/sparta/forusmarket/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/forusmarket/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: ✨feat, 🔧chore

#11 chore : 로컬 환경에서의 더미 데이터를 위한 profile 분리
  .gitignore
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🔧chore

#12 feat : 상품 더미 데이터 bulk insert
  build.gradle
  src/main/java/com/sparta/forusmarket/common/_dummydata/BatchInserter.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/DummyDataLoader.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/DummyStaticData.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/ProductGenerator.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/dto/ProductDto.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/utils/DateUtil.java
  src/main/java/com/sparta/forusmarket/common/_dummydata/utils/RandomUtil.java
  src/main/java/com/sparta/forusmarket/domain/order/entity/Order.java
  src/main/java/com/sparta/forusmarket/domain/order/enums/OrderStatus.java
  src/main/java/com/sparta/forusmarket/domain/product/entity/Product.java
  src/main/java/com/sparta/forusmarket/domain/product/enums/Category.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/forusmarket/domain/product/type/CategoryType.java
  src/main/java/com/sparta/forusmarket/domain/product/type/SubCategoryType.java
  src/test/java/com/sparta/forusmarket/DataFakerTest.java
  src/test/java/com/sparta/forusmarket/RandomDataTest.java
Labels: ✅test, ✨feat, 🔧chore

#16 feat: 프로필 조회 API
  .env.local
  src/main/java/com/sparta/forusmarket/domain/user/controller/UserController.java
  src/main/java/com/sparta/forusmarket/domain/user/dto/response/UserResponse.java
  src/main/java/com/sparta/forusmarket/domain/user/service/UserService.java
  src/test/java/com/sparta/forusmarket/domain/user/service/UserServiceTest.java
Labels: ✅test, ✨feat

#18 fix: 회원탈퇴 메서드명 수정
  src/main/java/com/sparta/forusmarket/domain/auth/controller/AuthController.java
Labels: 🐛fix

#21 feat : 단일 상품 조회 API
  src/main/java/com/sparta/forusmarket/domain/product/controller/ProductController.java
  src/main/java/com/sparta/forusmarket/domain/product/exception/ProductErrorCode.java
  src/main/java/com/sparta/forusmarket/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/sparta/forusmarket/domain/product/service/ProductService.java
  src/test/java/com/sparta/forusmarket/domain/product/service/ProductServiceTest.java
Labels: ✅test, ✨feat

#34 Feat/hot keyword
  src/main/java/com/sparta/forusmarket/common/config/CachingConfig.java
  src/main/java/com/sparta/forusmarket/common/config/JacksonConfig.java
  src/main/java/com/sparta/forusmarket/common/config/RedisConfig.java
  src/main/java/com/sparta/forusmarket/domain/hotKeywords/controller/HotKeywordsController.java
  src/main/java/com/sparta/forusmarket/domain/hotKeywords/dto/HotKeywordsResponse.java
  src/main/java/com/sparta/forusmarket/domain/hotKeywords/entity/HotKeywords.java
  src/main/java/com/sparta/forusmarket/domain/hotKeywords/repository/HotKeywordsRepository.java
  src/main/java/com/sparta/forusmarket/domain/hotKeywords/service/HotKeywordsService.java
  src/main/java/com/sparta/forusmarket/domain/product/controller/ServiceController.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductRepository.java
Labels: ✨feat

#32 fix: 주문 생성 수정, 주문 응답 dto변경
  build.gradle
  src/main/java/com/sparta/forusmarket/common/repository/RedisLockRepository.java
  src/main/java/com/sparta/forusmarket/domain/log/aop/OrderLogAspect.java
  src/main/java/com/sparta/forusmarket/domain/order/controller/OrderController.java
  src/main/java/com/sparta/forusmarket/domain/order/dto/request/OrderRequest.java
  src/main/java/com/sparta/forusmarket/domain/order/dto/response/OrderResponse.java
  src/main/java/com/sparta/forusmarket/domain/order/entity/Order.java
  src/main/java/com/sparta/forusmarket/domain/order/enums/OrderStatus.java
  src/main/java/com/sparta/forusmarket/domain/order/exception/OrderErrorCode.java
  src/main/java/com/sparta/forusmarket/domain/order/exception/OrderFailedException.java
  src/main/java/com/sparta/forusmarket/domain/order/exception/OrderNotFoundException.java
  src/main/java/com/sparta/forusmarket/domain/order/service/OrderService.java
  src/main/java/com/sparta/forusmarket/domain/product/entity/Product.java
  src/main/java/com/sparta/forusmarket/domain/product/service/ProductService.java
  src/main/java/com/sparta/forusmarket/domain/user/dto/AddressDto.java
  src/test/java/com/sparta/forusmarket/domain/order/service/OrderServiceIntegrationTest.java
  src/test/java/com/sparta/forusmarket/domain/order/service/OrderServiceTest.java
  src/test/resources/application-test.yml
Labels: 🐛fix

#38 fix : 상품 Request DTO 기본 생성자 누락
  src/main/java/com/sparta/forusmarket/domain/product/dto/request/ProductEditRequest.java
  src/main/java/com/sparta/forusmarket/domain/product/dto/request/ProductRegisterRequest.java
Labels: 🐛fix

#41 feat : 사용자 주문 로그 조회 API 구현
  src/main/java/com/sparta/forusmarket/domain/log/controller/OrderLogController.java
  src/main/java/com/sparta/forusmarket/domain/log/dto/response/OrderLogResponse.java
  src/main/java/com/sparta/forusmarket/domain/log/repository/OrderLogRepository.java
  src/main/java/com/sparta/forusmarket/domain/log/service/OrderLogService.java
Labels: ✨feat

#36 feat: 블랙리스트 기반 로그아웃 API 구현 및 RefreshToken Redis 저장
  lombok.config
  src/main/java/com/sparta/forusmarket/common/config/RedisConfig.java
  src/main/java/com/sparta/forusmarket/common/security/dto/RefreshToken.java
  src/main/java/com/sparta/forusmarket/common/security/dto/TokenResponse.java
  src/main/java/com/sparta/forusmarket/common/security/exception/InvalidHeaderException.java
  src/main/java/com/sparta/forusmarket/common/security/exception/SecurityErrorCode.java
  src/main/java/com/sparta/forusmarket/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/forusmarket/common/security/service/RedisBlacklistService.java
  src/main/java/com/sparta/forusmarket/common/security/service/RefreshTokenIssuer.java
  src/main/java/com/sparta/forusmarket/common/security/service/RefreshTokenService.java
  src/main/java/com/sparta/forusmarket/common/security/utils/CookieUtil.java
  src/main/java/com/sparta/forusmarket/common/security/utils/JwtUtil.java
  src/main/java/com/sparta/forusmarket/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/forusmarket/domain/auth/service/AuthService.java
  src/main/java/com/sparta/forusmarket/domain/user/entity/User.java
  src/main/java/com/sparta/forusmarket/domain/user/repository/UserRepository.java
  src/test/java/com/sparta/forusmarket/domain/auth/sevice/AuthServiceTest.java
  src/test/java/com/sparta/forusmarket/domain/security/service/RedisBlacklistServiceTest.java
  src/test/java/com/sparta/forusmarket/domain/security/service/RefreshTokenServiceTest.java
Labels: ✅test, ✨feat, 🐛fix, 🔧chore
