Repository sparta-4-s/For-Us-Market, pull requests merged in 2025-10, with the labels that each got.

#42 fix: RedisBlacklistServiceTest
  src/test/java/com/sparta/forusmarket/domain/security/service/RedisBlacklistServiceTest.java
Labels: 🐛fix

#46 feat : 상품 목록 조회 커버링 인덱스 적용
  src/main/java/com/sparta/forusmarket/domain/product/controller/ProductController.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductQueryRepository.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductQueryRepositoryImpl.java
  src/main/java/com/sparta/forusmarket/domain/product/service/ProductService.java
Labels: ⚡perf, ✨feat

#48 feat : no offset 기반 페이지네이션
  src/main/java/com/sparta/forusmarket/domain/product/controller/ProductController.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductQueryRepository.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductQueryRepositoryImpl.java
  src/main/java/com/sparta/forusmarket/domain/product/service/ProductService.java
Labels: ⚡perf, ✨feat

#51 feat: lock order
  build.gradle
  src/main/java/com/sparta/forusmarket/common/config/RedisConfig.java
  src/main/java/com/sparta/forusmarket/common/lock/Aspect/LettuceLockAspect.java
  src/main/java/com/sparta/forusmarket/common/lock/Aspect/RedissonLockAspect.java
  src/main/java/com/sparta/forusmarket/common/lock/aop/LettuceLock.java
  src/main/java/com/sparta/forusmarket/common/lock/aop/RedissonLock.java
  src/main/java/com/sparta/forusmarket/common/lock/repository/LettuceLockRepository.java
  src/main/java/com/sparta/forusmarket/common/lock/service/LettuceLockService.java
  src/main/java/com/sparta/forusmarket/common/lock/service/RedissonLockService.java
  src/main/java/com/sparta/forusmarket/common/repository/RedisLockRepository.java
  src/main/java/com/sparta/forusmarket/common/security/service/RedisBlacklistService.java
  src/main/java/com/sparta/forusmarket/common/security/service/RefreshTokenIssuer.java
  src/main/java/com/sparta/forusmarket/common/security/service/RefreshTokenService.java
  src/main/java/com/sparta/forusmarket/domain/log/aop/OrderLogAspect.java
  src/main/java/com/sparta/forusmarket/domain/order/controller/OrderController.java
  src/main/java/com/sparta/forusmarket/domain/order/dto/request/OrderRequest.java
  src/main/java/com/sparta/forusmarket/domain/order/service/OrderLockService.java
  src/main/java/com/sparta/forusmarket/domain/order/service/OrderService.java
  src/main/java/com/sparta/forusmarket/domain/product/entity/Product.java
  src/main/java/com/sparta/forusmarket/domain/product/repository/ProductRepository.java
  src/test/java/com/sparta/forusmarket/domain/order/service/OrderServiceIntegrationTest.java
Labels: ✨feat

#54 Create README.md
  README.md
Labels: 📝docs
